<a href="https://colab.research.google.com/github/shlee0619/workStats/blob/main/1126.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 확률

## z점수

In [ ]:
# 라이브러리 불러오기
import pandas as pd

In [ ]:
x = pd.Series([12, 15, 11, 13, 8, 14, 12, 13, 12, 10])

In [ ]:
# 평균
x_bar = x.mean();x_bar

12.0

In [ ]:
# 표준편차
s = x.std();s

2.0

In [ ]:
# z점수 = (관측치 - 평균)/표준편차
z_score = (x - x_bar)/s;z_score

0    0.0
1    1.5
2   -0.5
3    0.5
4   -2.0
5    1.0
6    0.0
7    0.5
8    0.0
9   -1.0
dtype: float64

In [ ]:
from scipy.stats import norm

In [ ]:
# 누적확률 = 누적분포함수
# 왼쪽에서 오른쪽으로 가면서 누적
norm.cdf(z_score)

array([0.5       , 0.9331928 , 0.30853754, 0.69146246, 0.02275013,
       0.84134475, 0.5       , 0.69146246, 0.5       , 0.15865525])

In [ ]:
# 오른쪽에서 왼쪽으로 가면서 누적
norm.cdf(-z_score)

array([0.5       , 0.0668072 , 0.69146246, 0.30853754, 0.97724987,
       0.15865525, 0.5       , 0.30853754, 0.5       , 0.84134475])

In [ ]:
# 함수 이용해서 z점수 계산
# 1) 불편추정치 표준편차 사용
from scipy.stats import zscore
zscore(x, ddof = 1)

0    0.0
1    1.5
2   -0.5
3    0.5
4   -2.0
5    1.0
6    0.0
7    0.5
8    0.0
9   -1.0
dtype: float64

In [ ]:
# StandardScaler 모델에 적용하기 위해 2차원 구조로 변경
x_df = pd.DataFrame({'x': x})

In [ ]:
# 2) 편향추정치 표준편차를 계산하여 결과를 반환
from sklearn import preprocessing
standard = preprocessing.StandardScaler()
standard.fit(x_df)
z_score = standard.transform(x_df)
z_score

array([[ 0.        ],
       [ 1.58113883],
       [-0.52704628],
       [ 0.52704628],
       [-2.10818511],
       [ 1.05409255],
       [ 0.        ],
       [ 0.52704628],
       [ 0.        ],
       [-1.05409255]])

In [ ]:
# 편향추정치를 이용하면 같은 결과 볼 수 있음
zscore(x, ddof = 0)

0    0.000000
1    1.581139
2   -0.527046
3    0.527046
4   -2.108185
5    1.054093
6    0.000000
7    0.527046
8    0.000000
9   -1.054093
dtype: float64

## 문제 풀이

In [ ]:
# 4번
x = pd.Series([55,50,60,58.5,46])

In [ ]:
x_bar = 50;x_sd = 5

In [ ]:
# z점수
(x - x_bar)/x_sd

0    1.0
1    0.0
2    2.0
3    1.7
4   -0.8
dtype: float64

In [ ]:
# 5번
# 원점수(관측치) = z점수*표준편차+평균
x_bar = 40;x_sd = 5;z_score = 1.5

In [ ]:
z_score * x_sd + x_bar

47.5

In [ ]:
# 6번
x = pd.Series([70,80,81,83,63])

In [ ]:
x_bar = 75;x_sd = 6.38

In [ ]:
# z점수
z_score = (x - x_bar)/x_sd
z_score

0   -0.783699
1    0.783699
2    0.940439
3    1.253918
4   -1.880878
dtype: float64

In [ ]:
from scipy.stats import norm
# 누적확률 = 누적분포함수
# 왼쪽에서 오른쪽으로 가면서 누적
cum_p = norm.cdf(z_score);cum_p

array([0.21660836, 0.78339164, 0.82650375, 0.89506418, 0.02999428])

In [ ]:
tab = pd.DataFrame({'x': x,
                    'z_score': z_score,
                    'cum_p': cum_p})

In [ ]:
tab

x   z_score     cum_p
0  70 -0.783699  0.216608
1  80  0.783699  0.783392
2  81  0.940439  0.826504
3  83  1.253918  0.895064
4  63 -1.880878  0.029994

In [ ]:
# 1) 70 ~ 80 확률 = 80 이하 확률 - 70 이하 확률
cum_p[1] - cum_p[0]

0.5667832855106969

In [ ]:
# 2) 80 보다 높을 확률 = 1 - 80 이하 확률
1 - cum_p[1]

0.21660835724465155

In [ ]:
# 3) 81 ~ 83 확률 = 83 이하 확률 - 81 이하 확률
cum_p[3] - cum_p[2]

0.06856042975493926

In [ ]:
# 4) 63 이하 확률
cum_p[4]

0.029994275757256352

# 단일표본검정

In [ ]:
# 아래 내용은 정규성을 가정하고 진행

## 1) 표본의 크기 상관 없이, 모분산(모표준편차)를 알고 있는 경우

In [ ]:
import numpy as np
from scipy.stats import norm

In [ ]:
# 1) 모표준편차를 알고 있는 경우
n = 36;N = 1000;x_bar = 100;mu = 99

In [ ]:
sd = 5;sigma = 2.5
var = sd ** 2;sigma2 = sigma ** 2

In [ ]:
print(n,N,x_bar,mu,sd,sigma,var,sigma2)

36 1000 100 99 5 2.5 25 6.25


In [ ]:
# 검정통계량 = z statistics
# 분자	표본평균-모평균
x_bar - mu

1

In [ ]:
# 분모	표준오차 = 모표준편차/제곱근(표본의 크기)
sigma/np.sqrt(n)

0.4166666666666667

In [ ]:
# 분자 / 분모
zv = (x_bar - mu) / (sigma/np.sqrt(n));zv

2.4

In [ ]:
# 임계값 = critical value
# 유의수준, 양측검정
alpha = 0.05
# 임계값에 해당하는 누적면적 = 1 - alpha/2 = 0.975
# ppf = 면적을 축의 값으로 변환
cv = norm.ppf(1 - alpha/2);cv

1.959963984540054

In [ ]:
# 결론
cv < zv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다
# 이번 학기 학생들의 평균과 지난 20년 동안의 학생들의 평균과 차이가 있다.

True

In [ ]:
# 유의확률
# = 검정통계량에 해당하는 면적
pv = 1 - norm.cdf(zv);pv = pv * 2;pv

0.01639507184919231

In [ ]:
# 결론
alpha > pv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다
# 이번 학기 학생들의 평균과 지난 20년 동안의 학생들의 평균과 차이가 있다.

True

In [ ]:
# 신뢰구간 confidence interval
# 표본평균 ± 임계값 * 표준오차
# 표준오차
se = sigma/np.sqrt(n)
# 하한값
lower_ci = x_bar - (cv * se)
# 상한값
upper_ci = x_bar + (cv * se)
# 신뢰구간 출력
print("신뢰구간: [", lower_ci, "-", upper_ci, "]")

신뢰구간: [ 99.18334833977498 - 100.81665166022502 ]


## 2) 모분산(모표준편차)을 몰라도 표본이 충분히 큰 경우(n > 30)

In [ ]:
# 2) 모표준편차를 알 수 없지만, 표본의 크기가 30 이상인 경우
x = [61, 78, 73, 92, 71, 83, 58, 78, 94, 57, 74, 76, 62, 91, 53, 60, 97, 55, 92, 60, 93, 100, 65, 53, 54, 66, 73, 89, 61, 57, 60, 51, 99, 77, 74, 58, 58, 71, 74, 92, 50, 73, 63, 59, 93, 94, 72, 89, 88, 66, 83, 71, 53, 87, 66, 87, 99, 57, 64, 57, 98, 51, 89, 100, 81, 61, 68, 92, 64, 93, 93, 76, 83, 70, 52, 86, 55, 70, 94, 91, 59, 73, 98, 81, 86, 61, 75, 86, 88, 93, 54, 51, 69, 63, 71, 92, 71, 97, 72, 92, 74]

In [ ]:
mu = 76
# 표본평균, 표본표준편차, 표본크기
x_bar = np.mean(x);x_sd = np.std(x, ddof = 1);n = len(x)
print(x_bar, x_sd, n)

74.5940594059406 15.05667839719092 101


In [ ]:
# 검정통계량
# 분자	표본평균-모평균
x_bar - mu

-1.4059405940594019

In [ ]:
# 분모	표준오차 = 표본표준편차/제곱근(표본의 크기)
x_sd/np.sqrt(n)

1.4981954966236297

In [ ]:
# 분자 / 분모
zv = (x_bar - mu) / (x_sd/np.sqrt(n));zv = abs(zv);zv

0.9384226539379301

In [ ]:
# 임계값
# 유의수준, 양측검정
alpha = 0.05
# 임계값에 해당하는 누적면적 = 1 - alpha/2 = 0.975
cv = norm.ppf(1 - alpha/2);cv

1.959963984540054

In [ ]:
# 결론
cv < zv
# 왼쪽 = 채택역 = 귀무가설 채택
# = 대립가설 기각 = 차이가 없다
# = 통계적으로 유의한 차이가 없다

False

In [ ]:
# 유의확률
# = 검정통계량에 해당하는 면적
pv = 1 - norm.cdf(zv);pv = pv * 2;pv

0.3480272484300375

In [ ]:
# 결론
alpha > pv
# 왼쪽 = 채택역 = 귀무가설 채택
# = 대립가설 기각 = 차이가 없다
# = 통계적으로 유의한 차이가 없다

False

In [ ]:
# 신뢰구간 confidence interval
# 표본평균 ± 임계값 * 표준오차
# 표준오차
se = x_sd/np.sqrt(n)
# 하한값
lower_ci = x_bar - (cv * se)
# 상한값
upper_ci = x_bar + (cv * se)
# 신뢰구간 출력
print("신뢰구간: [", lower_ci, "-", upper_ci, "]")

신뢰구간: [ 71.65765019075819 - 77.530468621123 ]


### 함수 사용하여 해보기

In [ ]:
# z검정 함수
def ztest(x, mu, sigma):
  zv = (np.mean(x) - mu) / (sigma/np.sqrt(len(x)))
  if zv < 0:
    zv = abs(zv)
  pv = (1 - norm.cdf(zv))* 2
  return(print("검정통계량: ", zv, "유의확률: ", pv))

In [ ]:
ztest(x = x, mu = mu, sigma = x_sd)

검정통계량:  0.9384226539379301 유의확률:  0.3480272484300375


## 3) 표본의 크기가 충분히 크지 않은 경우(n <= 30) & 모분산(모표준편차)를 모름

In [ ]:
from scipy.stats import t

In [ ]:
# 3) 모표준편차를 알 수 없고, 표본의 크기가 30 보다 작은 경우
mu = 500;x_bar = 513;x_sd = 73.77;n = 20
print(mu, x_bar, x_sd, n)

500 513 73.77 20


In [ ]:
# 검정통계량
# 분자	표본평균-모평균
x_bar - mu

13

In [ ]:
# 분모	표준오차 = 표본표준편차/제곱근(표본의 크기)
x_sd/np.sqrt(n)

16.49547347001595

In [ ]:
# 분자 / 분모
tv = (x_bar - mu) / (x_sd/np.sqrt(n));tv

0.7880949900365262

In [ ]:
# 임계값
# 유의수준, 양측검정
alpha = 0.1
# 자유도
df = n - 1;df

19

In [ ]:
# 임계값에 해당하는 누적면적 = 1 - alpha/2 = 0.95
cv = t.ppf(1 - alpha/2, df);cv

1.729132811521367

In [ ]:
# 결론
cv < tv
# 왼쪽 = 채택역 = 귀무가설 채택
# = 대립가설 기각 = 차이가 없다
# = 통계적으로 유의한 차이가 없다

False

In [ ]:
# 유의확률
# = 검정통계량에 해당하는 면적
pv = 1 - t.cdf(tv, df);pv = pv * 2;pv

0.44036346277833216

In [ ]:
# 결론
alpha > pv
# 왼쪽 = 채택역 = 귀무가설 채택
# = 대립가설 기각 = 차이가 없다
# = 통계적으로 유의한 차이가 없다

False

In [ ]:
# 신뢰구간 confidence interval
# 표본평균 ± 임계값 * 표준오차
# 표준오차
se = x_sd/np.sqrt(n)
# 하한값
lower_ci = x_bar - (cv * se)
# 상한값
upper_ci = x_bar + (cv * se)
# 신뢰구간 출력
print("신뢰구간: [", lower_ci, "-", upper_ci, "]")

신뢰구간: [ 484.4771355814152 - 541.5228644185848 ]


## 3번 케이스 - 정규성 검정하여 진행해보자

In [ ]:
# 가설 설정
# Ho = 모평균의 값은 76 이다. (모평균 = 표본평균)
# H1 = 모평균의 값은 76 이 아니다. (모평균 ≠ 표본평균)
# 유의수준 설정
# 기본적으로 0.05
# 검정통계량 / 유의확률 계산
# 귀무가설 기각 여부 판단 및 해석

In [ ]:
import pandas as pd
import scipy.stats as stats
from scipy.stats import shapiro
from scipy.stats import t
mu = 76
x = [61, 78, 73, 92, 71, 83, 58, 78, 94, 57, 74, 76, 62, 91, 53, 60, 97, 55, 92, 60]

In [ ]:
# 정규성 검정
print(shapiro(x))
pv = shapiro(x)[1]
alpha = 0.05
print(alpha > pv)
# 유의확률이 0.05 보다 작은지 큰지 확인
# False = 0.05 보다 크면 귀무가설 채택 = 정규성을 가짐
# True = 0.05 보다 작으면 귀무가설 기각 = 정규성을 가지지 않음

ShapiroResult(statistic=0.9163713537034351, pvalue=0.08438287022037215)
False


### 정규성 가지는 경우
- t-test

In [ ]:
from scipy.stats import ttest_1samp
tv, pv = ttest_1samp(a = x, popmean = mu)
print("검정통계량: ", abs(tv))
print("유의확률: ", pv)
# 0.05 보다 작으면 귀무가설 기각 = 차이가 있음
# 0.05 보다 크면 귀무가설 채택 = 차이가 없음
# 유의수준 0.05 에서 x 평균은 모평균과 같다고 할 수 있다.
# 여기서 주의할 점은 유의확률이 t분포를 사용한 결과 = 3번 케이스

# 신뢰구간
result = ttest_1samp(a = x, popmean = mu)
ci = result.confidence_interval()
print("신뢰구간: ", ci)
print("신뢰구간: ", round(ci[0], 2), "-", round(ci[1], 2))

검정통계량:  0.8440535541250771
유의확률:  0.4091414535785669
신뢰구간:  ConfidenceInterval(low=66.4307453194258, high=80.0692546805742)
신뢰구간:  66.43 - 80.07


### 정규성 가지지 않는 경우

In [ ]:
# 비모수 통계
# 윌콕슨 부호 순위 검정
stats.wilcoxon(pd.Series(x) - mu, alternative="two-sided")
# 0.05 보다 작으면 귀무가설 기각 = 차이가 있음
# 0.05 보다 크면 귀무가설 채택 = 차이가 없음

# 유의수준 0.05 에서 x 평균은 모평균과 같다고 할 수 있다.

WilcoxonResult(statistic=73.5, pvalue=0.38610669095577943)

## 6번

In [ ]:
x = [22402, 37205, 33931, 35347, 39892, 22705, 37290, 28060, 25047, 28541, 33301, 38738, 34655, 26029, 22329, 27007, 29143, 20961, 26025]

In [ ]:
mu = 35676
# 표본평균, 표본표준편차, 표본크기
x_bar = np.mean(x);x_sd = np.std(x, ddof = 1);n = len(x)
print(x_bar, x_sd, n)

29926.736842105263 6141.607153416814 19


In [ ]:
# 검정통계량
# 분자	표본평균-모평균
x_bar - mu

-5749.263157894737

In [ ]:
# 분모	표준오차 = 표본표준편차/제곱근(표본의 크기)
x_sd/np.sqrt(n)

1408.9813122458102

In [ ]:
# 분자 / 분모
tv = (x_bar - mu) / (x_sd/np.sqrt(n));tv = abs(tv);tv

4.0804396111761365

In [ ]:
# 임계값
# 유의수준, 양측검정
alpha = 0.05
# 자유도
df = n - 1;df

18

In [ ]:
# 임계값에 해당하는 누적면적 = 1 - alpha/2 = 0.975
cv = t.ppf(1 - alpha/2, df);cv

2.10092204024096

In [ ]:
# 결론
cv < tv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다

True

In [ ]:
# 유의확률
# = 검정통계량에 해당하는 면적
pv = 1 - t.cdf(tv, df);pv = pv * 2;pv

0.0007021250551453306

In [ ]:
# 결론
alpha > pv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다

True

In [ ]:
# 신뢰구간 confidence interval
# 표본평균 ± 임계값 * 표준오차
# 표준오차
se = x_sd/np.sqrt(n)
# 하한값
lower_ci = x_bar - (cv * se)
# 상한값
upper_ci = x_bar + (cv * se)
# 신뢰구간 출력
print("신뢰구간: [", lower_ci, "-", upper_ci, "]")

신뢰구간: [ 26966.57694892041 - 32886.896735290116 ]


In [ ]:
# 6번 문제
sales = [22402, 37205, 33931, 35347, 39892, 22705, 37290, 28060, 25047, 28541, 33301, 38738, 34655, 26029, 22329, 27007, 29143, 20961, 26025]
# 3) 표본의 크기가 충분히 크지 않은 경우(n <= 30) & 모분산(모표준편차)를 모름
mu = 35676

In [ ]:
# 정규성 검정
print(shapiro(sales))
pv = shapiro(sales)[1]
alpha = 0.05
print(alpha > pv)
# 유의확률이 0.05 보다 작은지 큰지 확인
# False = 0.05 보다 크면 귀무가설 채택 = 정규성을 가짐
# True = 0.05 보다 작으면 귀무가설 기각 = 정규성을 가지지 않음

ShapiroResult(statistic=0.9311549336700413, pvalue=0.1818824247085794)
False


In [ ]:
from scipy.stats import ttest_1samp
tv, pv = ttest_1samp(a = sales, popmean = mu)
print("검정통계량: ", abs(tv))
print("유의확률: ", pv)

검정통계량:  4.0804396111761365
유의확률:  0.000702125055145388


In [ ]:
# 신뢰구간
result = ttest_1samp(a = sales, popmean = mu)
ci = result.confidence_interval()
print("신뢰구간: ", ci)
print("신뢰구간: ", round(ci[0], 2), "-", round(ci[1], 2))

신뢰구간:  ConfidenceInterval(low=26966.57694892041, high=32886.896735290116)
신뢰구간:  26966.58 - 32886.9


# 독립표본 t검정

## 등분산 가정

In [ ]:
import numpy as np
from scipy.stats import t

In [ ]:
x1 =[7, 5, 5, 3, 4, 7, 3, 6, 1, 2, 10, 9, 3, 10, 2, 8, 5, 5, 8, 1, 2, 5, 1, 12, 8, 4, 15, 5, 3, 4]
x2 = [5, 3, 4, 4, 2, 3, 4, 5, 2, 5, 4, 7, 5, 4, 6, 7, 6, 2, 8, 7, 8, 8, 7, 9, 9, 5, 7, 8, 6, 6]

In [ ]:
# 표본평균, 표본분산, 표본크기, 자유도
x1_m = np.mean(x1);x2_m = np.mean(x2)
x1_s2 = np.var(x1, ddof = 1);x2_s2 = np.var(x2, ddof = 1)
n1 = len(x1);n2 = len(x2)
df1 = n1 - 1;df2 = n2 -1
print(x1_m,x2_m,x1_s2,x2_s2,n1,n2,df1,df2)

5.433333333333334 5.533333333333333 11.702298850574715 4.257471264367816 30 30 29 29


In [ ]:
# 통합분산추정치 = (1표본자유도*1표본분산+2표본자유도*2표본분산) / (전체자유도 = 1표본크기 - 1 + 2표본크기 - 1)
# 분자 = (1표본자유도*1표본분산+2표본자유도*2표본분산)
df1 * x1_s2 + df2 * x2_s2

462.83333333333337

In [ ]:
# 분모 = 전체자유도
df1 + df2

58

In [ ]:
# 분자/분모
sp2 = (df1 * x1_s2 + df2 * x2_s2)/(df1 + df2);sp2

7.979885057471265

In [ ]:
# 검정통계량 = (1표본평균 - 2표본평균) / 제곱근(통합분산/1표본크기 + 통합분산/2표본크기)
# 분자 = (1표본평균 - 2표본평균)
x1_m - x2_m

-0.09999999999999964

In [ ]:
# 분모 = 제곱근(통합분산/1표본크기 + 통합분산/2표본크기)
np.sqrt((sp2/n1) + (sp2/n2))

0.7293780481785499

In [ ]:
# 분자/분모
tv = (x1_m - x2_m)/np.sqrt((sp2/n1) + (sp2/n2))
tv = abs(tv);tv

0.13710311168498437

In [ ]:
# 임계값, 유의수준 0.05, 양측검정, 자유도
alpha = 0.05
df = df1 + df2;df

58

In [ ]:
# 1 - alpha/2 = 0.975
# ppf = 면적 => 축의 값
cv = t.ppf(1 - alpha/2, df);cv

2.0017174841452356

In [ ]:
# 결론 => 우리가 원하는 결과 cv < tv => True
cv < tv
# 왼쪽 = 채택역 = 귀무가설 채택
# = 대립가설 기각 = 차이가 없다
# = 통계적으로 유의한 차이가 없다

False

In [ ]:
# 유의확률
pv = (1 - t.cdf(tv, df)) * 2; pv

0.8914241208918985

In [ ]:
# 결론 => 우리가 원하는 결과 alpha > pv => True
alpha > pv
# 왼쪽 = 채택역 = 귀무가설 채택
# = 대립가설 기각 = 차이가 없다
# = 통계적으로 유의한 차이가 없다

False

## 정규성, 등분산검정으로 진행

In [ ]:
# 가설 설정
# Ho = 두 모평균 사이의 차이는 없다. (모평균1 = 모평균2)
# H1 = 두 표본평균 사이의 차이는 있다. (표본평균1 ≠ 표본평균2)
# 유의수준 설정
# 기본적으로 0.05
# 정규성, 등분산성 가설검정
# 검정통계량 / 유의확률 계산
# 귀무가설 기각 여부 판단 및 해석

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import shapiro
from scipy.stats import ttest_ind
import matplotlib.pyplot as plt
from scipy.stats import t

In [ ]:
x1 =[7, 5, 5, 3, 4, 7, 3, 6, 1, 2, 10, 9, 3, 10, 2, 8, 5, 5, 8, 1, 2, 5, 1, 12, 8, 4, 15, 5, 3, 4]
x2 = [5, 3, 4, 4, 2, 3, 4, 5, 2, 5, 4, 7, 5, 4, 6, 7, 6, 2, 8, 7, 8, 8, 7, 9, 9, 5, 7, 8, 6, 6]

In [ ]:
# 정규성 검정
print(shapiro(x1))
print(shapiro(x2))
# 유의확률이 0.5 보다 작은지 큰지 확인
# 0.5 보다 작으면 귀무가설 기각 = 정규성을 가지지 않음
# 0.5 보다 크면 귀무가설 채택 = 정규성을 가짐

ShapiroResult(statistic=0.9292907629575096, pvalue=0.047020254400976895)
ShapiroResult(statistic=0.9518999172467568, pvalue=0.1900303953744074)


#### 정규성 가지는 경우
- 등분산 검정

#### 등분산검정

In [ ]:
# 레빈 - 정규성 만족 안함
from scipy.stats import levene
levene(x1, x2)

LeveneResult(statistic=3.342862412393952, pvalue=0.0726409738218915)

### 기타 등분산 검정

In [ ]:
# 바틀렛 - 정규성 만족
from scipy.stats import bartlett
bartlett(x1, x2)

BartlettResult(statistic=6.995618330032188, pvalue=0.008170947838026072)

In [ ]:
# 플리그너 - 정규성 만족 안함, 더 안정적 결과
from scipy.stats import fligner
fligner(x1, x2)

FlignerResult(statistic=3.508273694910684, pvalue=0.061063051338622554)

### 등분산 가정

In [ ]:
# 기본값 equal_var = True
# ttest_ind(x1, x2)
ttest_ind(x1, x2, equal_var = True)

TtestResult(statistic=-0.13710311168498437, pvalue=0.8914241208918983, df=58.0)

In [ ]:
from scipy.stats import ttest_ind
# tv, pv = ttest_ind(x1, x2)
tv, pv = ttest_ind(x1, x2, equal_var = True)
print("검정통계량: ", abs(tv))
print("유의확률: ", pv)

검정통계량:  0.13710311168498437
유의확률:  0.8914241208918983


In [ ]:
print(np.mean(x1))
print(np.mean(x2))

5.433333333333334
5.533333333333333


### 이분산 가정

In [ ]:
from scipy.stats import ttest_ind
# 기본값 equal_var = True
ttest_ind(x1, x2, equal_var = False)

TtestResult(statistic=-0.13710311168498437, pvalue=0.8915271547944409, df=47.63474735627105)

In [ ]:
from scipy.stats import ttest_ind
tv, pv = ttest_ind(x1, x2, equal_var = False)
print("검정통계량: ", abs(tv))
print("유의확률: ", pv)

검정통계량:  0.13710311168498437
유의확률:  0.8915271547944409


### 정규성 가지지 않는 경우

In [ ]:
# 비모수 검정
# Mann–Whitney U test
stats.mannwhitneyu(x1, x2, alternative="two-sided")
# 0.05 보다 작으면 귀무가설 기각 = 차이가 있음
# 0.05 보다 크면 귀무가설 채택 = 차이가 없음

MannwhitneyuResult(statistic=405.0, pvalue=0.5075449838388612)

## 문제1

In [ ]:
# 문제1
import numpy as np
from scipy.stats import t

In [ ]:
# x1 = 남학생, x2 = 여학생
x1 = [9, 8, 4, 9, 3, 8, 10, 8, 9, 8, 10, 7, 6, 12]
x2 = [3, 5, 1, 2, 6, 4, 3, 6, 7, 9, 7, 3, 7, 6, 8, 8]

In [ ]:
# 표본평균, 표본분산, 표본크기, 자유도
x1_m = np.mean(x1);x2_m = np.mean(x2)
x1_s2 = np.var(x1, ddof = 1);x2_s2 = np.var(x2, ddof = 1)
n1 = len(x1);n2 = len(x2)
df1 = n1 - 1;df2 = n2 -1
print(x1_m,x2_m,x1_s2,x2_s2,n1,n2,df1,df2)

7.928571428571429 5.3125 5.60989010989011 5.695833333333334 14 16 13 15


In [ ]:
# 등분산 가정
# 통합분산추정치 = (1표본자유도*1표본분산+2표본자유도*2표본분산) / (전체자유도 = 1표본크기 - 1 + 2표본크기 - 1)
# 분자 = (1표본자유도*1표본분산+2표본자유도*2표본분산)
df1 * x1_s2 + df2 * x2_s2

158.36607142857144

In [ ]:
# 분모 = 전체자유도
df1 + df2

28

In [ ]:
# 분자/분모
sp2 = (df1 * x1_s2 + df2 * x2_s2)/(df1 + df2);sp2

5.6559311224489806

In [ ]:
# 검정통계량 = (1표본평균 - 2표본평균) / 제곱근(통합분산/1표본크기 + 통합분산/2표본크기)
# 분자 = (1표본평균 - 2표본평균)
x1_m - x2_m

2.616071428571429

In [ ]:
# 분모 = 제곱근(통합분산/1표본크기 + 통합분산/2표본크기)
np.sqrt((sp2/n1) + (sp2/n2))

0.8703394598247217

In [ ]:
# 분자/분모
tv = (x1_m - x2_m)/np.sqrt((sp2/n1) + (sp2/n2))
tv = abs(tv);tv

3.005805837067621

In [ ]:
# 임계값, 유의수준 0.05, 단측검정, 자유도
alpha = 0.05
df = df1 + df2;df

28

In [ ]:
# 1 - alpha = 0.95
cv = t.ppf(1 - alpha, df);cv

1.701130934265931

In [ ]:
# 결론 => 우리가 원하는 결과 cv < tv => True
cv < tv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다

True

In [ ]:
# 유의확률
pv = (1 - t.cdf(tv, df));pv

0.00276863108877079

In [ ]:
# 결론 => 우리가 원하는 결과 alpha > pv => True
alpha > pv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다
# 남학생과 여학생의 손을 드는 횟수 평균 차이가 있다.
# 남학생의 손을 드는 평균 횟수가 여학생보다 많다.

True

## 함수 이용

In [ ]:
from scipy.stats import shapiro
# 정규성 검정
print(shapiro(x1))
print(shapiro(x2))
# 유의확률이 0.5 보다 작은지 큰지 확인
# 0.5 보다 작으면 귀무가설 기각 = 정규성을 가지지 않음
# 0.5 보다 크면 귀무가설 채택 = 정규성을 가짐

ShapiroResult(statistic=0.9348924727368566, pvalue=0.35680274749035434)
ShapiroResult(statistic=0.9470001883759136, pvalue=0.44370520099354616)


In [ ]:
# 등분산 검정, 레빈
from scipy.stats import levene
levene(x1, x2)
# p-value < 0.05 => 차이가 있다 = 분산이 다르다 = 이분산가정
# p-value > 0.05 => 차이가 없다 = 분산이 같다 = 등분산가정

LeveneResult(statistic=0.2663173064325955, pvalue=0.6098644945678466)

In [ ]:
from scipy.stats import ttest_ind
# 기본값 equal_var = True
# 단측검정 alternative = 'greater'
ttest_ind(x1, x2, alternative = 'greater')
# ttest_ind(x1, x2, equal_var = True)

TtestResult(statistic=3.005805837067621, pvalue=0.002768631088770782, df=28.0)

In [ ]:
from scipy.stats import ttest_ind
tv, pv = ttest_ind(x1, x2, alternative = 'greater')
print("검정통계량: ", abs(tv))
print("유의확률: ", pv)

검정통계량:  3.005805837067621
유의확률:  0.002768631088770782


In [ ]:
print(np.mean(x1))
print(np.mean(x2))

7.928571428571429
5.3125


## 문제2

In [ ]:
# 문제2
# 임계값, 유의수준 0.01, 양측검정, 자유도
alpha = 0.01
df = df1 + df2;df

28

In [ ]:
# 1 - alpha/2 = 1 - 0.01/2
cv = t.ppf(1 - alpha/2, df);cv

2.763262455461066

In [ ]:
# 결론 => 우리가 원하는 결과 cv < tv => True
cv < tv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다

True

In [ ]:
# 유의확률
pv = (1 - t.cdf(tv, df)) * 2;pv

0.00553726217754158

In [ ]:
# 결론 => 우리가 원하는 결과 alpha > pv => True
alpha > pv
# 오른쪽 = 기각역 = 귀무가설 기각
# = 대립가설 채택 = 차이가 있다
# = 통계적으로 유의한 차이가 있다
# 남학생과 여학생의 손을 드는 평균 횟수에 차이가 있다.

True

## 함수 이용

In [ ]:
# 정규성 검정
print(shapiro(x1))
print(shapiro(x2))
# 유의확률이 0.5 보다 작은지 큰지 확인
# 0.5 보다 작으면 귀무가설 기각 = 정규성을 가지지 않음
# 0.5 보다 크면 귀무가설 채택 = 정규성을 가짐

ShapiroResult(statistic=0.9348924727368566, pvalue=0.35680274749035434)
ShapiroResult(statistic=0.9470001883759136, pvalue=0.44370520099354616)


In [ ]:
# 등분산 검정, 레빈
from scipy.stats import levene
levene(x1, x2)
# p-value < 0.05 => 차이가 있다 = 분산이 다르다 = 이분산가정
# p-value > 0.05 => 차이가 없다 = 분산이 같다 = 등분산가정

LeveneResult(statistic=0.2663173064325955, pvalue=0.6098644945678466)

In [ ]:
from scipy.stats import ttest_ind
# 기본값 equal_var = True
ttest_ind(x1, x2)
# ttest_ind(x1, x2, equal_var = True)

TtestResult(statistic=3.005805837067621, pvalue=0.005537262177541564, df=28.0)

In [ ]:
from scipy.stats import ttest_ind
tv, pv = ttest_ind(x1, x2)
print("검정통계량: ", abs(tv))
print("유의확률: ", pv)

검정통계량:  3.005805837067621
유의확률:  0.005537262177541564


In [ ]:
print(np.mean(x1))
print(np.mean(x2))

7.928571428571429
5.3125
